version: "3"

services:
  namenode:
    image: ppfenning/hadoop-namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=big_data
    env_file:
      - ./hadoop.env

  datanode0:
    image: ppfenning/hadoop-datanode
    container_name: datanode0
    restart: always
    depends_on: [namenode]
    volumes:
      - hadoop_datanode0:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode1:
    image: ppfenning/hadoop-datanode
    container_name: datanode1
    restart: always
    depends_on: [namenode]
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode0:
  hadoop_datanode1:
