version: "3.8"

services:

  wordcount:
    build:
      context: ../../${BACKEND}
      args:
        IMAGE_FAMILY: "${IMAGE_FAMILY}"
        BACKEND: "${BACKEND}"
        TAG: "${TAG}"
    image: "${IMAGE_FAMILY}-${BACKEND}:${TAG}"
    volumes:
      - ./WordCount.jar:/opt/hadoop/applications/WordCount.jar
      - ./wordcount.sh:/scripts/wordcount.sh
    environment:
      # wordcount specific
      JAR_FILEPATH: /opt/hadoop/applications/WordCount.jar
      CLASS_TO_RUN: "WordCount"
      PARAMS: "/input /output"
      # check for namenode
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ../../env_files/hadoop.env
    command: bash -c "chmod a+x /scripts/wordcount.sh && /scripts/wordcount.sh"
