version: "3.8"

services:

  hivenode:
    container_name: hivenode
    build:
      context: .
      args:
        IMAGE_FAMILY: "${IMAGE_FAMILY}"
        BACKEND: "${BACKEND}"
        TAG: "${TAG}"
    image: "${IMAGE_FAMILY}-hive-${BACKEND}:${TAG}"
    env_file:
      - ../env_files/hadoop.env
      - ../env_files/hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    healthcheck:
      test: [ "CMD", "test", "-f", "./.hive_init" ]
      timeout: 45s
      interval: 10s
      retries: 5
    ports:
      - "10000:10000"
    command:
      - ./startup/start-hive.sh
