version: "3.8"

services:

  hive-metastore:
    build:
      context: .
      args:
        IMAGE_FAMILY: "${IMAGE_FAMILY}"
        BACKEND: "${BACKEND}"
        TAG: "${TAG}"
    image: "${IMAGE_FAMILY}-hive-${BACKEND}:${TAG}"
    container_name: hive-meta
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9083/" ]
      timeout: 45s
      interval: 10s
      retries: 5
    env_file:
      - ../env_files/hadoop.env
      - ../env_files/hive.env
    command: hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9083:9083"

  hive-server:
    container_name: hive-server
    build:
      context: .
      args:
        IMAGE_FAMILY: "${IMAGE_FAMILY}"
        BACKEND: "${BACKEND}"
        TAG: "${TAG}"
    image: "${IMAGE_FAMILY}-hive-${BACKEND}:${TAG}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10000/" ]
      timeout: 45s
      interval: 10s
      retries: 5
    env_file:
      - ../env_files/hadoop.env
      - ../env_files/hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore-postgresql:
    container_name: hive-postgres
    build:
      context: .
      args:
        IMAGE_FAMILY: "${IMAGE_FAMILY}"
        BACKEND: "${BACKEND}"
        TAG: "${TAG}"
    image: "${IMAGE_FAMILY}-hive-${BACKEND}:${TAG}"
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    env_file:
      - ../env_files/hadoop.env
      - ../env_files/hive.env

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    container_name: presto
    ports:
      - "8888:8888"
