version: "3.8"

services:

  datanode:
    build: ..
    image: "${IMAGE_FAMILY}-hadoop:${TAG}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9864/" ]
      timeout: 45s
      interval: 10s
      retries: 5
    expose:
      - "9864"
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/datanode
    environment:
      HDFS_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ../../env_files/hadoop.env
    command:
      - ./startup/start-datanode.sh

volumes:
  hadoop_datanode:
